const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto'),url=require('url');
let Pool=null;
if(process.env.DATABASE_URL){Pool=require('pg').Pool}
const ROOT=__dirname,PORT=Number(process.env.PORT||8080),BASE=process.env.PUBLIC_BASE_URL||'';
const PROD=process.env.NODE_ENV==='production',SESSION_TTL=43200000,RATE_WINDOW=60000,MAX_LOGIN=8;
const legacyHash=p=>crypto.createHash('sha256').update(String(p)).digest('hex');
const scryptHash=p=>{const salt=crypto.randomBytes(16).toString('hex');const dk=crypto.scryptSync(String(p),salt,64);return 'scrypt$'+salt+'$'+dk.toString('hex')};
const verify=(stored,p)=>{try{if(stored?.startsWith('scrypt$')){const [,salt,key]=stored.split('$');return crypto.timingSafeEqual(Buffer.from(key,'hex'),crypto.scryptSync(String(p),salt,64))}return stored===legacyHash(p)}catch{return false}};
const pool=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL,ssl:PROD?{rejectUnauthorized:false}:undefined}):null;
const localDB=path.join(ROOT,'data.json');
const localSeed={users:[{id:'u1',name:'Owner Bandar',username:'owner',password:legacyHash('owner123'),role:'owner'},{id:'u2',name:'Kasir Bandar',username:'kasir',password:legacyHash('kasir123'),role:'cashier'},{id:'u3',name:'Barista Bandar',username:'barista',password:legacyHash('barista123'),role:'barista'},{id:'u4',name:'Pelanggan Demo',username:'customer',password:legacyHash('customer123'),role:'customer'}],products:[{id:'p1',name:'Kopi Susu Bandar',price:18000,category:'Kopi'},{id:'p2',name:'Americano',price:15000,category:'Kopi'},{id:'p3',name:'Cappuccino',price:20000,category:'Kopi'},{id:'p4',name:'Matcha Latte',price:22000,category:'Non-Kopi'},{id:'p5',name:'Croissant',price:16000,category:'Makanan'}],tables:Array.from({length:12},(_,i)=>({id:'t'+(i+1),name:'Meja '+String(i+1).padStart(2,'0'),status:'available',qrToken:'BK-'+(i+1)})),orders:[],sessions:{}};
if(!pool&&!fs.existsSync(localDB))fs.writeFileSync(localDB,JSON.stringify(localSeed,null,2));
const memSessions=new Map(),clients=new Set(),attempts=new Map();
const security={'X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'strict-origin-when-cross-origin','Permissions-Policy':'camera=(), microphone=(), geolocation=()','Cache-Control':'no-store'};
function send(res,status,obj,extra={}){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8',...security,...extra});res.end(JSON.stringify(obj))}
function body(req){return new Promise((resolve,reject)=>{let b='';req.on('data',c=>{b+=c;if(b.length>1000000)reject(Error('Payload terlalu besar'))});req.on('end',()=>{try{resolve(b?JSON.parse(b):{})}catch{reject(Error('JSON tidak valid'))}})})}
function cookie(req,n){const m=(req.headers.cookie||'').match(new RegExp('(?:^|; )'+n+'=([^;]+)'));return m?.[1]}
function limited(ip){const now=Date.now(),a=(attempts.get(ip)||[]).filter(t=>now-t<RATE_WINDOW);if(a.length>=MAX_LOGIN){attempts.set(ip,a);return true}a.push(now);attempts.set(ip,a);return false}
function csrf(req){if(!['POST','PATCH','DELETE'].includes(req.method))return true;const o=req.headers.origin;if(!o)return true;try{return o===new URL(BASE||'http://'+(req.headers.host||'localhost')).origin}catch{return false}}
async function q(text,params=[]){if(!pool)throw Error('PostgreSQL tidak aktif');return (await pool.query(text,params)).rows}
async function usersFind(username){if(pool)return (await q('SELECT * FROM users WHERE username=$1',[username]))[0];return JSON.parse(fs.readFileSync(localDB)).users.find(x=>x.username===username)}
async function userById(id){if(pool)return (await q('SELECT id,name,username,role FROM users WHERE id=$1',[id]))[0];return JSON.parse(fs.readFileSync(localDB)).users.find(x=>x.id===id)}
async function products(){if(pool)return q('SELECT id,name,price,category FROM products WHERE active=true ORDER BY id');return JSON.parse(fs.readFileSync(localDB)).products.filter(x=>x.active!==false)}
async function tables(){if(pool)return q('SELECT id,name,status,qr_token AS "qrToken" FROM tables ORDER BY id');return JSON.parse(fs.readFileSync(localDB)).tables}
async function orders(){if(pool)return q(`SELECT id,customer_id AS "customerId",customer_name AS "customerName",table_name AS table,items,total,status,payment,payment_status AS "paymentStatus",created_at AS "createdAt",updated_at AS "updatedAt" FROM orders ORDER BY created_at DESC`);return JSON.parse(fs.readFileSync(localDB)).orders}
async function saveSession(token,userId){if(pool)return q('INSERT INTO user_sessions(token,user_id,created_at) VALUES ($1,$2,now()) ON CONFLICT(token) DO UPDATE SET user_id=EXCLUDED.user_id,created_at=now()',[token,userId]);memSessions.set(token,{userId,createdAt:Date.now()})}
async function auth(req){const token=cookie(req,'bk_session');if(!token)return null;if(pool){const r=await q(`SELECT u.id,u.name,u.username,u.role,s.created_at FROM user_sessions s JOIN users u ON u.id=s.user_id WHERE s.token=$1`,[token]);if(!r[0])return null;if(Date.now()-new Date(r[0].created_at).getTime()>SESSION_TTL){await q('DELETE FROM user_sessions WHERE token=$1',[token]);return null}return r[0]}const s=memSessions.get(token);if(!s||Date.now()-s.createdAt>SESSION_TTL){memSessions.delete(token);return null}return userById(s.userId)}
async function createOrder(x,u,publicQR=false){const t=publicQR?(await tables()).find(v=>v.qrToken===x.tableToken):null;if(publicQR&&!t)throw Error('QR meja tidak valid');const items=Array.isArray(x.items)?x.items:[];if(!items.length)throw Error('Pesanan kosong');const total=items.reduce((a,i)=>a+Number(i.price||0)*Number(i.qty||1),0);const id='ORD-'+Date.now().toString(36).toUpperCase();const tableId=t?.id||null,tableName=t?.name||x.table||'Takeaway',customerId=u?.id||null,customerName=x.customerName||u?.name||'Pelanggan QR',payment=x.payment||'CASH';
if(pool){const r=await q(`INSERT INTO orders(id,customer_id,customer_name,table_id,table_name,items,total,status,payment,payment_status) VALUES($1,$2,$3,$4,$5,$6,$7,'NEW',$8,'UNPAID') RETURNING id,customer_id AS "customerId",customer_name AS "customerName",table_name AS table,items,total,status,payment,payment_status AS "paymentStatus",created_at AS "createdAt"`,[id,customerId,customerName,tableId,tableName,JSON.stringify(items),total,payment]);return r[0]}
const d=JSON.parse(fs.readFileSync(localDB));const o={id,customerId,customerName,tableId,table:tableName,items,total,status:'NEW',payment,paymentStatus:'UNPAID',createdAt:new Date().toISOString()};d.orders.unshift(o);fs.writeFileSync(localDB,JSON.stringify(d,null,2));return o}
function broadcast(){for(const r of clients){try{r.write('event: update\\ndata: '+JSON.stringify({at:Date.now()})+'\\n\\n')}catch{clients.delete(r)}}}
function serve(req,res){let p=url.parse(req.url).pathname;if(p==='/')p='/index.html';const f=path.join(ROOT,p.replace(/\\/g,'/'));if(!f.startsWith(ROOT)||!fs.existsSync(f)){res.writeHead(404,security);return res.end('Not found')}const ext=path.extname(f),ct={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json','.css':'text/css','.png':'image/png','.svg':'image/svg+xml'}[ext]||'text/plain';res.writeHead(200,{'Content-Type':ct,...security,'Cache-Control':ext==='.png'?'public,max-age=86400':'no-cache'});fs.createReadStream(f).pipe(res)}
const server=http.createServer(async(req,res)=>{try{const p=url.parse(req.url).pathname;if(!csrf(req))return send(res,403,{error:'Origin tidak diizinkan'});if(req.method==='OPTIONS'){res.writeHead(204,{...security,'Access-Control-Allow-Origin':BASE||'*','Access-Control-Allow-Credentials':'true','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'GET,POST,PATCH,OPTIONS'});return res.end()}
if(p==='/health')return send(res,200,{ok:true,version:'3.4',database:!!pool,time:new Date().toISOString()});
if(p==='/api/events'){res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive',...security});res.write('event: hello\\ndata: {}\\n\\n');clients.add(res);req.on('close',()=>clients.delete(res));return}
if(p==='/api/login'&&req.method==='POST'){const ip=req.socket.remoteAddress||'unknown';if(limited(ip))return send(res,429,{error:'Terlalu banyak percobaan login. Coba lagi nanti.'});const x=await body(req),u=await usersFind(x.username);if(!u||!verify(u.password,x.password||''))return send(res,401,{error:'Username/password salah'});if(pool&& !String(u.password).startsWith('scrypt$'))await q('UPDATE users SET password=$1 WHERE id=$2',[scryptHash(x.password||''),u.id]);const token=crypto.randomBytes(32).toString('hex');await saveSession(token,u.id);return send(res,200,{user:{id:u.id,name:u.name,role:u.role}},{'Set-Cookie':`bk_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=43200${PROD?'; Secure':''}`})}
if(p==='/api/logout'&&req.method==='POST'){const token=cookie(req,'bk_session');if(pool)await q('DELETE FROM user_sessions WHERE token=$1',[token]);else memSessions.delete(token);return send(res,200,{ok:true},{'Set-Cookie':`bk_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0${PROD?'; Secure':''}`})}
const u=await auth(req);if(p==='/api/me')return send(res,200,{user:u?{id:u.id,name:u.name,role:u.role}:null});
if(p==='/api/products')return send(res,200,await products());if(p==='/api/tables')return send(res,200,await tables());
if(p==='/api/public/table'){const token=url.parse(req.url,true).query.token,t=(await tables()).find(x=>x.qrToken===token);if(!t)return send(res,404,{error:'QR meja tidak valid'});return send(res,200,{table:{id:t.id,name:t.name,token:t.qrToken},products:await products()})}
if(p==='/api/public/orders'&&req.method==='POST'){const o=await createOrder(await body(req),u,true);broadcast();return send(res,201,o)}
if(p==='/api/orders'&&req.method==='GET'){if(!u)return send(res,401,{error:'Login diperlukan'});return send(res,200,await orders())}
if(p==='/api/orders'&&req.method==='POST'){if(!u)return send(res,401,{error:'Login diperlukan'});const o=await createOrder(await body(req),u,false);broadcast();return send(res,201,o)}
const m=p.match(/^\/api\/orders\/([^/]+)\/status$/);if(m&&req.method==='PATCH'){if(!u||!['owner','cashier','barista'].includes(u.role))return send(res,403,{error:'Tidak berwenang'});const st=(await body(req)).status;if(!['NEW','PROCESSING','READY','DONE','CANCELLED'].includes(st))return send(res,400,{error:'Status tidak valid'});if(pool){const r=await q(`UPDATE orders SET status=$1,updated_at=now() WHERE id=$2 RETURNING id,customer_id AS "customerId",customer_name AS "customerName",table_name AS table,items,total,status,payment,payment_status AS "paymentStatus",created_at AS "createdAt",updated_at AS "updatedAt"`,[st,m[1]]);if(!r[0])return send(res,404,{error:'Order tidak ditemukan'});broadcast();return send(res,200,r[0])}const d=JSON.parse(fs.readFileSync(localDB)),o=d.orders.find(v=>v.id===m[1]);if(!o)return send(res,404,{error:'Order tidak ditemukan'});o.status=st;o.updatedAt=new Date().toISOString();fs.writeFileSync(localDB,JSON.stringify(d,null,2));broadcast();return send(res,200,o)}
if(p==='/api/dashboard'){if(!u||u.role!=='owner')return send(res,403,{error:'Owner only'});if(pool){const r=await q(`SELECT COALESCE(SUM(total),0) omzet,COUNT(*) transactions,COUNT(*) FILTER(WHERE status='DONE') done,COUNT(*) FILTER(WHERE status NOT IN('DONE','CANCELLED')) pending FROM orders`);return send(res,200,r[0])}const os=await orders(),done=os.filter(o=>o.status==='DONE');return send(res,200,{omzet:done.reduce((a,o)=>a+Number(o.total||0),0),transactions:os.length,done:done.length,pending:os.filter(o=>!['DONE','CANCELLED'].includes(o.status)).length})}
serve(req,res)}catch(e){console.error(e);send(res,500,{error:e.message})}});
server.listen(PORT,()=>console.log(`Bandar Kopi V3.4 running on ${PORT} | postgres=${!!pool}`));
